### ISSUE TITLE
Incorrent Markdown syntax highlighting

### ISSUE THREAD

**Issue by Birdie0** [idleberg/vscode-hopscotch#2]
Markdown syntax highlighting is incorrect for

* hyperlinks (closing square bracket has same color as text inside brackers)
* alternate variant of h1 tag (with =) isn't highlighed

![screenshot at 2017-07-05 15-28-01](https://user-images.githubusercontent.com/7945905/27864318-bd1b9768-6196-11e7-9868-04a0bffdad8f.png)

**Comment by idleberg** [comment]
This bug is inherited from the [base16 template](https://github.com/chriskempson/base16-builder/blob/master/templates/textmate/dark.tmTheme.erb), but they don't accept any PR anymore.

Anyway, if I remember correctly, this is already fixed in 0.2. I can't say when I get to releasing it – “soon”.
