### ISSUE TITLE
Will you be updating this to include theming for the rest of the window?

### ISSUE THREAD

**Issue by loganintech** [idleberg/vscode-hopscotch#3]
New versions of VSCode's theme engine allows for recoloring of tabs, the bottom bar, the workbench on the right, and even more stuff. Are there any plans to support those?

**Comment by idleberg** [comment]
Yes, eventually I want to color the rest of the workbench as well – v0.2 was a first step towards that goal. I don't use VSCode in my daily work, which is why this might take some time. I'll try and get to it in September.

**Comment by jcklpe** [comment]
Hey love this theme @idleberg :) I was wondering if it was supposed to work with javascript? When I write a sample piece of text like in the screenshot (which I think is python?) it doesn't look quite right color wise: 

![image](https://user-images.githubusercontent.com/9451726/58389485-89a9dc80-7ff0-11e9-95fb-4c53adba4772.png)

The quotes aren't green and new isn't blue. But maybe I'm just missing a difference based in the syntax of the languages?

Also do you have any recommended resources for writing one's own theme. I've heavily modified your theme using a combination of a regex based hilighting extension, css injection extension, and lastly setting theme token settings in my settings.json file. I want a cleaner and easier to share experience though. I imagien the regex and css injection will probably have to be separate files etc but I'd at least like to get the token settings etc out of my settings file. And make it easier for people to actually install it themselves etc. 

Thanks!

**Comment by idleberg** [comment]
> When I write a sample piece of text like in the screenshot (which I think is python?) it doesn't look quite right color wise

The screenshot is a generic Ruby example created by `base16-builder`. Color scheme and language syntax are separate things. A language syntax (or grammar) describes which keywords there are and assigns them into categories (e.g. variables, integers, functions etc.) - [see this article](https://manual.macromates.com/en/language_grammars). A color scheme colors these categories with no knowledge of the language. Hence, the same color scheme might produce different results across languages and even within two different language syntaxes for the same language.

> Also do you have any recommended resources for writing one's own theme

Actually I don't. I've only defined some [Base16](http://chriskempson.com/projects/base16/)-compatible colors and ran them through `base16-builder`. In the case of Visual Studio Code, I merely published my existing TextMate/Sublime Text scheme, it's basically the same file.

**Comment by loganintech** [comment]
I hate to be _that guy_ but I was wondering if any progress has been made on this issue.
