### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by joaomaridalho** [idleberg/vscode-hopscotch#4]
Hi,

What is the font configuration you're using in VS Code, installed the theme and doesn't look as nice 

Best Regards,
João Maridalho

**Comment by idleberg** [comment]
The screenshot is generated by [base16-builder](https://github.com/chriskempson/base16-builder), the font [should be](https://github.com/chriskempson/base16-builder/blob/master/templates/preview/html.erb#L11) Menlo.
