### ISSUE TITLE
XML not colored?

### ISSUE THREAD

**Issue by Graloth** [idleberg/vscode-hopscotch#5]
I rarely work with XML files, so it confused me, when vscode colored it all white.

Is XML not supported by the Hopscotch color theme?

**Comment by idleberg** [comment]
That's not how VSCode color themes work. A theme provides colors for [scope selectors](https://manual.macromates.com/en/language_grammars#naming_conventions), not for specific language grammar (that's what Notepad++ does and it's plain stupid). The scope selectors are defined in the language grammar.

So, what does this mean? XML grammar is pre-installed with VSCode, so unless you tinkered deep in the editor's settings or file-structure, it should work. A good way to test this is to switch color themes. If there's a problem with the grammar, none of your theme will color XML. Also make sure the file you loaded is detected as XML, which might not happen when your file uses a non-standard file-extension.

**Comment by Graloth** [comment]
You are correct, it's not displaying any color on any theme, so it must be something with the XML, thanks for the help!
