### ISSUE TITLE
Some keywords aren't properly highlighted

### ISSUE THREAD

**Issue by sbstp** [idleberg/vscode-hopscotch#6]
![](https://i.imgur.com/MJGNwoP.png)

I would expect `not` and `in` to be highlighted in pink here. It seems to not be highlighted because of the [operators rule](https://github.com/idleberg/vscode-hopscotch/blob/master/themes/hopscotch.json#L54), `in`, `not`, `and`, `or` are treated as operators in Python. If not in pink, maybe another color, but it being plain-colored reduces readability.

**Comment by idleberg** [comment]
It sounds like an issue with your grammar, since color schemes are language agnostic. What happens when you use other color schemes?

**Comment by sbstp** [comment]
Yes they are:
default theme
![](https://i.imgur.com/uJ5zpO3.png)
material
![](https://i.imgur.com/W1jlawk.png)

**Comment by sbstp** [comment]
In the default vs theme, they managed to have numerical operators (+, -, <=, etc) be white and text operators (not, in, or, and) be blue.

**Comment by idleberg** [comment]
I will build it again using the latest [base16](https://github.com/chriskempson/base16-textmate)-templates, maybe the issue was fixed. Otherwise, I'd ask you to report it to them.

**Comment by sbstp** [comment]
I think I [found](https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_vs.json#L304) what the default theme uses to fix python keywords. I believe the issue could be fixed by adding the `keyword.operator.logical.python` scope to the  `"Keywords"` rule, but I understand if you don't want to diverge from the base16 theme.

**Comment by idleberg** [comment]
Thanks for the info. I don't plan to divert from base16, but if it hasn't been fixed in more recent versions, I can submit a pull-request (unless you want prefer to do so yourself). Today is a bit busy, but I should have plenty of time for this tomorrow!

**Comment by sbstp** [comment]
Ok thanks! For now I've patched the issue with these settings. I guess in the end it's just a quirk of Python because it has both text and symbol operators.
```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "name": "-",
            "scope": "keyword.operator.logical.python",
            "settings": {
                "foreground": "#c85e7c"
            }
        }
    ]
},
```
